# Streamlit secrets file
# Add your API keys and other sensitive information here

# API keys section (used by config.py)
[api_keys]
openai = ""
semantic_scholar = "your-semantic-scholar-api-key"

# Credentials section
[credentials]
email = "your-email@example.com"

# Database settings
[database]
path = "./chroma_db"

# Model settings
[settings]
default_model = "gpt-4o"
embedding_model = "text-embedding-3-small"

# Also keep the original format for backward compatibility
OPENAI_API_KEY = "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"
